Fix: move_in and move_out re-added
TimUntersberger/nog pull request #215
Opened 2021-01-21 00:00 UTC by ramirezmike

This is just filling in the bindings for move_in and move_out that got lost in all the changes I think.

2021-01-21 07:24 UTC, TimUntersberger requested changes
Could you add documentation for these two functions? I think I forgot to write documentation too. Sorry about that!

2021-01-22 01:59 UTC, ramirezmike commented
>Could you add documentation for these two functions?

Totally, no worries. I want to make sure I'm looking at it right: would it just be adding stuff into the mdbook stuff in src/book? I imagine it'd be under some documentation for nog.workspaces but I don't think I see that there?

2021-01-22 05:58 UTC, TimUntersberger commented
You would have to add it to the doc-gen subproject under nogscript. The doc generation is still a bit faulty so the Api reference is still missing from the book subproject.

2021-01-27 03:33 UTC, ramirezmike commented
I added some docs to doc-gen/nogscript/nog/workspace.ns but wasn't sure if you wanted it added anywhere else. I think some of these might be good to have a picture or gif with showing an example. Anyway if this works let me know and I can merge it if you haven't and we can get rid of the development branch or whatever.

2021-01-28 19:41 UTC, merged