[WIP] Tiling and Workspace fixes
TimUntersberger/nog pull request #224
Opened 2021-01-30 04:50 UTC by ramirezmike

Leaving this as a WIP to discuss the changes. I'll try to keep this original post updated.

This pull request contains the following commits...
1. Workspaces remain ordered by ID
    I noticed that moving workspaces back and forth across monitors changes the order of them. If you have the following...
      monitor1            monitor2
      1 2 3  7                 5 6
and then moving workspace  5 back to monitor 1 it ends up like this
      monitor1            monitor2
      1 2 3  7 5                6     
This commit keeps the order so it ends up "1 2 3 5 7"

2. made right-alt usage configurable
This is in regards to #210 and just adds a config value to allow usage of the right alt. This is just an initial attempt at it, open to suggestions on a better implementation. Still need to add documentation, but that's dependent on if we decide this is a good idea or not.

3. prevent unmanaging windows from inactive workspaces
  This tripped me up a bit a couple times but basically if you switch to another workspace it's possible depending on what windows are currently visible that you still have focus on a window that was on the workspace you just left... and if you toggle to manage/unmanage a window at this point it unmanages the window from the workspace that isn't currently visible. This is more likely to happen when working across multiple monitors and losing track of what window on what workspace you think is focused. 

    This commit just adds some logic to prevent unmanaging the window if it's not on the focused workspace since it's unlikely the user wants that to happen. I also went ahead and renamed a couple functions like find_window and find_grid as their names were incorrect; find_window returns a grid and find_grid returns a display, so I renamed them to find_grid_containing_window and find_grid_display. 

4. #211 fix columns and rows merge
This should be pretty straight forward and is just adding logic for a scenario I documented in #211 that I came across. Also added unit tests for this one.

Other things I'm considering adding to this request if I have time:

- [ ] Add a move workspace to another workspace, i.e, moving all the tiles on workspace 3 to workspace 9
- [ ] Re-add missing ignore_fullscreen_actions checks

2021-02-03 03:24 UTC, ramirezmike commented on twm/src/keybindings.rs
> +    pub fn update_configuration(&self, config: &Config) {
this is probably the most debatable part of this commit. I needed a way to flip the allow_right_alt value that is used in the loop further below, so I added this function that would be used for any other hot_reload type configuration changes in the future.

2021-02-03 19:29 UTC, TimUntersberger requested changes

2021-02-03 19:29 UTC, TimUntersberger commented on doc-gen/nogscript/nog/workspace.ns
> +/// Moves the focused workspace to the workspace that has the given index.
Should probably explain what "moving" a workspace to another workspace means.

2021-02-04 01:12 UTC, ramirezmike commented on doc-gen/nogscript/nog/workspace.ns
> +/// Moves the focused workspace to the workspace that has the given index.
Updated this:

/// Moves all windows in the focused workspace to the workspace that has 
/// the given index while maintaining relative sizes and positions. 
/// The target workspace must be empty. This allows you to transfer
/// an entire workspace to an empty workspace of a different number.
/// @param id Number

2021-02-04 01:14 UTC, ramirezmike commented
Going to change this from draft and mark it as "RDY." Still open to suggestions but I think this is about as much as I'll add to this pull request.

2021-02-04 21:27 UTC, TimUntersberger commented
@ramirezmike the PR is still a draft.

2021-02-08 18:46 UTC, merged